### ISSUE TITLE
Image recognition module

### ISSUE THREAD

**Issue by lukasStuber** [lukasStuber/Mobile_Robotics_Project#3]
Recognize the cars, parking spots, obstacles, etc.
Input:
A set of images taken by the camera

Output:
A list or dictionary of the objects, containing the label (spot, car, obstacle) and the coordinates

**Comment by begoodpoussin** [comment]
based on exercise session 2

Also, maybe use feature recognition to differenciate type of obstacles ? 
differenciate parking walls with other obstacle ? [have to get closer in order to park?]
