### ISSUE TITLE
Main loop module

### ISSUE THREAD

**Issue by lukasStuber** [lukasStuber/Mobile_Robotics_Project#7]
Command sensor reading, state estimation, command motors and keeps track of the current state.
Input:
Sensor measurements, state estimations

Output:
Motor control

**Comment by begoodpoussin** [comment]
> Command sensor reading,  and keeps track of the current state.

J'ai l'impression que ça ce sera fait directement dans le local avoidance, car ça peut être un evenement qui se déclenche à chaque coup du timer, donc en continu automatique toutes les 10ms par exemple
