### ISSUE TITLE
Local obstacle avoidance module

### ISSUE THREAD

**Issue by lukasStuber** [lukasStuber/Mobile_Robotics_Project#8]
Gets activated when there is an obstacle detected

**Comment by begoodpoussin** [comment]
Work based on exercises session 4 : Local Navigation

Goal : 
- When there is an obstacle detected, this module gets activated to avoid obstacle
- Determine all the possible obstacles (borders, edge of table, moving obstacles), and avoid them while following the global path. 

Input : 
Output : 

KeyWords : Proximity sensors, local occupancy grid and global map from sensor values and displacements.
